version: "3.9"

services:
  sqlserver_dw:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_dw
    restart: unless-stopped
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      MSSQL_PID: Express
    ports:
      - "${SQLSERVER_PORT:-1433}:1433"
    volumes:
      - sqlserver_dw_data:/var/opt/mssql

volumes:
  sqlserver_dw_data: